### ISSUE TITLE
List initialization (i.e. list <int> test = [1, 2, 3];) and lists greater than size 4.

### ISSUE THREAD

**Issue by hjoo** [mgouzenko/flow-lang#21]

**Comment by hjoo** [comment]
lists greater than size 4 work now.

**Comment by adamchel** [comment]
This will probably need to be done by adding a line in the translate C adding each value to the back (or front, whichever is less intensive), unless we want to change the init code to support initializers. I think we should go for the latter, and I can implement that after the Edwards meeting tomorrow.
